### ISSUE TITLE
Allow emails with plus sign

### ISSUE THREAD

**Issue by hugopeixoto** [phstc/putsbox#1]
Hi, I was trying putsbox and noticed that when I send emails to account+SOMETHING@putsbox.com,
the email doesn't get delivered.

Is there any chance that you could add this feature? I'm not sure if this is handled in the rails app.

**Comment by phstc** [comment]
hi @hugopeixoto 

I tried `pablo+test@putsbox.com` and I got the email:

![screen shot 2016-01-18 at 3 03 28 pm](https://cloud.githubusercontent.com/assets/105652/12397497/abbcb37c-bdf4-11e5-99d3-8781e30bc7ca.png)

But it isn't like Gmail where `pablo+test@putsbox.com` is a label for `pablo`. PutsBox recognizes `pablo+test` as an email, not as an alias.
