### ISSUE TITLE
my putsbox email gets deleted every week

### ISSUE THREAD

**Issue by chiragverma** [phstc/putsbox#11]
my putsbox email gets deleted every week. It never used to happen before.

**Comment by phstc** [comment]
Hi @Chiragverma 

I don't control that much, I use a [capped collection](https://docs.mongodb.com/manual/core/capped-collections/) in MongoDB, so basically, when the collection is full, it deletes old documents.

> once a collection fills its allocated space, it makes room for new documents by overwriting the oldest documents in the collection.

I guess PutsBox is getting more traffic these days, causing records to be removed faster.

**Comment by chiragverma** [comment]
ah i see, okie no worries then.
