### ISSUE TITLE
Allow GET /inspect with the full email

### ISSUE THREAD

**Issue by sadortun** [phstc/putsbox#12]
Hi,

It would make the life easier if you could accept both the `mailbox` and `email` as valid GET: 
- http://putsbox.com/JerryAColeman/inspect
- http://putsbox.com/JerryAColeman@putsbox.com/inspect

Thanks,
Samuel

**Comment by phstc** [comment]
Hi @sadortun 

Is there a specific use case for `@putsbox.com`? 

PutsBox does not support any other domain.

**Comment by sadortun** [comment]
Yes, very simple, we already have a test dataset. And we could save a rwgex and substr if we could use the full email as identifier.  `http://putsbox.com/[[ user.email ]]/inspect`. Otherwise we need to save it in an other field.

Also in future, having more than one domain related to a putbox installation would be nice ,
