### ISSUE TITLE
Putsbox Down

### ISSUE THREAD

**Issue by vm-natarajan** [phstc/putsbox#14]
Hi - We are seeing Putsbox is down now,and any idea when will be available?

**Comment by phstc** [comment]
hi @mani0303 

The free Heroku quota was exceed. I added a paid Dyno, should be good now.

Just out of my curiosity, how do you use PutsBox? Just to know how users, use it 😄

**Comment by vm-natarajan** [comment]
Hi @phstc - Thank You.I was just running some Selenium based tests with email verification.Putsbox seems neat and clean without login hussles:)

**Comment by fentonfentonfenton** [comment]
We love putsbox! We've got it integrated into our capybara e2e tests. Don't think we use the UI anymore, just cURL tho, it does seem to be a bit slower at the moment.. but we're patient.

thank you putsbox!

**Comment by fentonfentonfenton** [comment]
feel free to ask more, we can show your our ruby if you want to know :)

**Comment by phstc** [comment]
@jfbookingbug I was just curious, thanks for clarifying.

**Comment by phstc** [comment]
> we can show your our ruby if you want to know :)

@jfbookingbug sure, can you share it?

**Comment by MariusJorgensen** [comment]
Hey! 

Seems like this is happening again?

**Comment by phstc** [comment]
Hi @MariusJorgensen 

It seems to be working now, maybe it was something temporary on Heroku.

**Comment by MariusJorgensen** [comment]
Yep, @phstc – might have been 👍

**Comment by ituradastra** [comment]
Hi, just a heads up that putsbox is down again at the moment. Thanks for creating this usefull app :)

**Comment by phstc** [comment]
@sanjapa thanks for reporting it - PutsBox is back again!

**Comment by ituradastra** [comment]
Thanks !!!! @phstc

**Comment by uniqa-lv** [comment]
Hi, PutsBox is down again. There is some Application error message.

**Comment by ituradastra** [comment]
I am experiencing the same error

**Comment by Zorba10-Star** [comment]
I am experiencing the same error

**Comment by bughunterqa** [comment]
Hi, Currently, emails haven't arrived in the mail for the last 4 days. Could you please check this issue

**Comment by ituradastra** [comment]
I am experiencing the same issue

**Comment by ashwin1224** [comment]
Is there some on going issue with putsbox? no emails are being received.
