### ISSUE TITLE
Trouble Setting up Putsbox locally

### ISSUE THREAD

**Issue by EricLiuCY** [phstc/putsbox#16]
Receiving following error:
/usr/local/lib/ruby/gems/2.5.0/gems/devise-4.4.0/lib/devise/rails/routes.rb:500:in `raise_no_secret_key': Devise.secret_key was not set. Please add the following to your Devise initializer: (RuntimeError)

I did set secret_key_base with ENV variable ENV['SECRET_TOKEN'] and replaced it with a token.

Also, any idea on how to use putsbox for automation tests in python?

**Comment by phstc** [comment]
Hi @EricLiuCY 

You also need to set `DEVISE_SECRET_KEY`.

https://github.com/phstc/putsbox/blob/f1a913055dc897fb690068e96c47fad4a8f7fcc2/config/initializers/devise.rb#L7

> Also, any idea on how to use putsbox for automation tests in python?

WDYT? I have a post for automating with Ruby: http://www.pablocantero.com/blog/2015/08/05/test-emails-with-automated-testing-tools/, I believe Python must have something similar.

**Comment by EricLiuCY** [comment]
@phstc 

Thanks for the tips. Tried what you said, still receiving the same error.

**Comment by phstc** [comment]
@EricLiuCY did you try `SECRET_TOKEN=some-value DEVISE_SECRET_KEY=some-value rails server`?

**Comment by EricLiuCY** [comment]
@phstc 

Yes. I set both the secret_key_base in secret_token.rb and the secret_key in in devise.rb. Also always used rails server after rails restart. Thank you so much for your help!
