### ISSUE TITLE
Clear History Button does not work.

### ISSUE THREAD

**Issue by Ivaylo-Bachvarov** [phstc/putsbox#17]
Hey! 

Thanks for the great tool!

Just reporting that the clear history button does not really work :( I am getting a error 500 when I click.

Cheers,

**Comment by phstc** [comment]
Hi @Ivaylo-Bachvarov 

Thanks for reporting it. I've just deployed the fix, could you try it again?

**Comment by Ivaylo-Bachvarov** [comment]
Great! Cheers :beers:
