### ISSUE TITLE
Environement and setup instructions ?

### ISSUE THREAD

**Issue by sadortun** [phstc/putsbox#2]
Hi Pablo,

First of all, great tools !    It would be nice if you could add to your Readme the list of dependencies and  basic how-to configure the app environement.

Thanks,
Samuel

**Comment by phstc** [comment]
Hi @sadortun 

Great idea! :beers: I added some steps on the [README](https://github.com/phstc/putsbox#getting-started) based on what I have for [PutsReq](https://github.com/phstc/putsreq).
