### ISSUE TITLE
Why u use GNU LESSER GENERAL PUBLIC LICENSE?

### ISSUE THREAD

**Issue by i5heu** [phstc/putsbox#20]
https://github.com/phstc/putsbox/blob/42933fd075fa210c143f2aaa3274188892bb122b/LICENSE#L4

"Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed."

-> so nobody can contribute Code to this.

Why u use this kind of License?

**Comment by phstc** [comment]
There are similar issues regarding to the licensing: https://github.com/phstc/shoryuken/issues?utf8=%E2%9C%93&q=license

Shoryuken is based on Sidekiq, therefore it must use LGPLv3.

> -> so nobody can contribute Code to this.

That is not how LGPLv3 works. You can change it, but you need to contribute back to the source. If you only use it as a library (gem), without changing Shoryuken itself, you don't need to contribute back.
