### ISSUE TITLE
Add classes and ids for easier selecting with selenium.

### ISSUE THREAD

**Issue by Ivaylo-Bachvarov** [phstc/putsbox#21]
Hey!

I'm using putsbox for my end to end tests and it seems like it works great. However most of the DOM elements that I need to access does not have any ids or classes. So the only choice that I have is to use xpath. xpath is ugly and if you change something in the html my tests are going to fail.

I'm thinking for adding classes and ids for some of the key DOM elements. Like: "Clear History Button", "Number of received emails" etc.

Can you share some input on that so I can create a PR?

**Comment by phstc** [comment]
Hi @Ivaylo-Bachvarov 

hm I don't know how it would work, for auto setting IDs or classes, wouldn't that need to be based on some sort of XPath? If so, every time the markup changes, the IDs or classes would also change. 

Also one of the ideas of PutsBox, is to make sure you test the e-mails as is, if PutsBox mutates the e-mail body, it might lead into false-positives.

How are you thinking on implementing this?

**Comment by Ivaylo-Bachvarov** [comment]
I didn`t explain my idea right. 

Example:
I want to assert that I have only one email received. So I open the /inspect page with selenium and I have to select the emails count with xpath because the DOM element that shows the number of new emails does not have class or id.

I'm not talking for adding classes to the emails. My idea is to add classes only to the elements in putsbox.

**Comment by phstc** [comment]
@Ivaylo-Bachvarov ah got it, thanks for the explanation.

I'm fine with adding IDs to the elements. I would avoid using classes for non-styling reasons. I would rather use `data-` attributes if necessary.

**Comment by Ivaylo-Bachvarov** [comment]
Great! Will try to find some time this week to create a PR.

**Comment by phstc** [comment]
Hi @Ivaylo-Bachvarov 👋 

👀 this issue again. I found out that it has a `data-` attributes already, and you could use those for getting the count. 

![image](https://user-images.githubusercontent.com/105652/79521628-a0ea2200-8027-11ea-9ed8-2d21b5a920e6.png)

```javascript
const inputToken = document.getElementById("putsbox-token-input")
inputToken.getAttribute("data-bucket-emails-count")
inputToken.getAttribute("data-bucket-token")
```

**Comment by phstc** [comment]
BTW https://putsbox.com/YOUR-EMAIL/inspect.json (**.json**) gives you a JSON with all emails.
