### ISSUE TITLE
Putsbox is down

### ISSUE THREAD

**Issue by meghanataraj** [phstc/putsbox#22]
@phstc Not able to receive mails through API. Getting 404 most of the times. Though was able to find mail couple of times, Issue is intermittent. Any idea when will it be available again?

**Comment by phstc** [comment]
Hi @meghanataraj 

I will double check it, the e-mail should be available for a few minutes before getting expired, but when the traffic is higher then can get expired sooner.

**Comment by meghanataraj** [comment]
Thanks for the info @phstc Able to access mails. We are using putsbox APIs for our API automation mail scenarios. putsbox is a great solution for email scenarios.
