### ISSUE TITLE
Need APIs to access

### ISSUE THREAD

**Issue by vigneshwar-v** [phstc/putsbox#26]
:pushpin: <s>#28</s>

**Comment by phstc** [comment]
Hi @vigneshwar-v 

Could you add more details to the issue?

**Comment by vigneshwar-v** [comment]
Any Webservice access to automate the mail verification process. Like rest calls to read emails??

**Comment by phstc** [comment]
Hi @vigneshwar-v 

Sorry for taking long on this. I've added a JSON representation support.

Now you can access https://putsbox.com/whatever-recipient-you-want-to/inspect.json to get your inbox as a JSON.

I update [this](http://www.pablocantero.com/blog/2015/08/05/test-emails-with-automated-testing-tools/) post with some extra info as well. 

Thanks for the feedback. 

Please let me know if that works for you.
