### ISSUE TITLE
Attachements ?

### ISSUE THREAD

**Issue by sadortun** [phstc/putsbox#3]
Hi!

IT look like inline attachments are discarded. Is it normal ?

Thanks,
Samuel

**Comment by phstc** [comment]
Hi @sadortun 

PutsBox ignores attachments.

**Comment by sadortun** [comment]
Hi Pablo,

I totally understand for security concern, and the storage issues that keeping attachements cause. But could you consider the following ....

Since attatchements are  read anyway by the mail `client`, You could expose the following, without causing security issues, or be impacted by storage limitations :

Expose the list of attachements  
- filenames
- Sizes
- MD5 / SHA ( insert favorite hashing algortym here )

That way, we could test that the attachements were correctly sent within the email.

Thanks,
Samuel

**Comment by phstc** [comment]
Hi Samuel,

That's actually a good idea, I can try to implement something like that.

Just out of my curiosity, could you give more details on your use case? How
are you using PutsBox?

BTW Currently, PutsBox uses Mandrill for free, but due the Mailchimp change, I
will need to move from Mandrill to another alternative for Inbound emails,
which I need to check the API for attachments.

Thanks

**Comment by sadortun** [comment]
https://www.mailgun.com/  worth looking at ! First 10k emails free.

For our use case, we have a system that generate notifications, some of theses notifications includes attachments like the invoice, or other documents. We can unit-test that the invoice is correctly generated, but we are looking at a simple way to ensure that the invoice is actually sent with the email. Simply checking if the file is there is a good start, but if we can also use [insert your favorite hashing algorithm here] to ensure the right file is delivered, it would be even better ! 

Thanks,
Samuel

**Comment by phstc** [comment]
Hey @sadortun 

Thanks for the recommendation :beers: 

I'm giving a try to SendGrid. It offers 12k for free, let's see how it goes :pray:  

Does `attachments` on the JSON format work for you?

![screen shot 2016-03-20 at 6 09 08 pm](https://cloud.githubusercontent.com/assets/105652/13907174/e1809c14-eec6-11e5-8295-96665ce1e140.png)

**Comment by sadortun** [comment]
It would be nice to have the size, and a hash.
