### ISSUE TITLE
Longer than typical email arrival (2+min)

### ISSUE THREAD

**Issue by Dirt11B** [phstc/putsbox#30]
I've noticed this week that it has taken far longer than normal for emails to appear in the buckets.  Beyond the usual SMTP few second delay, on average it seems to be around a 2-minute wait to be able to access emails via emailname/last OR appearing on the emailname/inspect page.

I have confirmed that the emails are being sent immediately and receive them at a normal speed on standard email services.

New to using PutsBox, but absolutely love it as a newer selenium user.  I am currently utilizing it to handle the registration confirmation emails for my automation tests in our organization's web portals.

**Comment by phstc** [comment]
Hi @Dirt11B 

Thanks for your feedback. I've just did a quick test and it seems to be working fine ATM. But depending on the volume of e-mails it can get slower. 

For ensuring performance, I would recommend running your own version of PutsBox.  Unfortunately, PutsBox runs on very limited resources.

**Comment by Dirt11B** [comment]
Thank you for the quick reply.

I'll look into getting a local version set up then, thanks again!
