### ISSUE TITLE
Is possible clear email by routes

### ISSUE THREAD

**Issue by crfnunes** [phstc/putsbox#35]
I found the clear route (like bellow), but when try execute (delete http method) is returned 422 status code. 
Can you help-me?

https://putsbox.com/recip/clear

Thanks.

**Comment by phstc** [comment]
Hi @crfnunes 

There's also a delete button.

![image](https://user-images.githubusercontent.com/105652/73757308-0c199d00-4737-11ea-9eab-cfa52801d20b.png)

That clear route works, but you need to make a POST request with a param `_method=delete`.

![image](https://user-images.githubusercontent.com/105652/73757404-30757980-4737-11ea-9b30-9f85fa53d556.png)

It also requires the `authenticity_token`.

**Comment by crfnunes** [comment]
Is it possible to get authenticity_token?

thank you!

**Comment by phstc** [comment]
@crfnunes it is generated per page on the page view. What's your use-case? You want to clear it programmatically? 

You can always create a new bucket too. That might be more straightforward.

**Comment by crfnunes** [comment]
Yes, I need clean email history programmatically.
Is it possible create new buckets by routes?

**Comment by phstc** [comment]
@crfnunes yes. you can make requests to https://putsreq.com/ANY-DYNAMIC-BUCKET-NAME-YOU-WANT then check it later with `/inspect`. You don't need to click on `create bucket` for provision one. It gets auto-provisioned on a request basis.
