### ISSUE TITLE
Putsbox not receiving emails

### ISSUE THREAD

**Issue by smithschreiner** [phstc/putsbox#42]
Example inbox: clotilde@putsbox.com

I have not been able to receive and emails in putsbox for any of the inbox I have created for a few hours now. Started testing around 9:30 AM EST. Still having issues at 12:20 EST. I have sent emails from various locations without success.

**Comment by phstc** [comment]
Hi @smithschreiner 

It seems to be working now. I couldn't find any related errors in the logs. 

Can you check it again?

**Comment by smithschreiner** [comment]
It appears to be working now. The only thing I could find was this message, "can't send yet, verification pending (re-send invitation)" while attempting to use one of the putsbox email addresses in putsmail. But I am not sure if it is remotely related. This was the email that was not verified 'dante_lynch@putsmail.com'
