### ISSUE TITLE
HTML Emails

### ISSUE THREAD

**Issue by ghost** [phstc/putsbox#5]
I am getting following error on some HTML emails in awcomputing@putsbox.com:

**We're sorry, but something went wrong.
If you are the application owner check the logs for more information.**

Any idea?

**Comment by phstc** [comment]
Hi @schmidh 

I tried to send a simple email to awcomputing@putsbox.com and it worked. The emails you are sending to awcomputing@putsbox.com have something special? Attachments?  Long long subject/body?

**Comment by phstc** [comment]
@schmidh are you still facing that error?

**Comment by chiragverma** [comment]
@phstc , I am also having this issue. The emails I am sending does not having anything special

**Comment by phstc** [comment]
Hi @Chiragverma can you send me a link to the error page?

**Comment by chiragverma** [comment]
@phstc, the email i am sending to putsbox contains two lines and has a url in it. Here is the error I get. 

![capture](https://cloud.githubusercontent.com/assets/4514534/23866116/32207acc-07ee-11e7-9768-a8a990390582.JPG)

**Comment by chiragverma** [comment]
this is what my email contains

You can click the link below to log into QA's copy for SmartSimple or use the password OCHTNKBQH.

https://qa.smartsimpleqa.com/ex/ex_activate.jsp?lang=1&token=%24zFo5eWiQba8NAtMKUMi%2FiPOr7SvMhz%2B2uPcp8RKXCflGEGy9RTQRcVPBh4kThzbD6lbgu4PWx%2BF5%0AzJeW6jTleQ%3D%3D

It opens fine in text format but get the error above when I open that in HTML

**Comment by phstc** [comment]
@Chiragverma would you mind copying and pasting the URL in the screenshot?

**Comment by chiragverma** [comment]
@phstc I am sorry but which URL?

**Comment by phstc** [comment]
@Chiragverma <img width="691" alt="screen shot 2017-03-13 at 13 22 25" src="https://cloud.githubusercontent.com/assets/105652/23866746/2000a45a-07f0-11e7-832f-c9c9066aac99.png">

**Comment by chiragverma** [comment]
here you go - http://preview.putsbox.com/p/lucas/58c6d5ee9f5795000c0002b6.html

**Comment by phstc** [comment]
Nice! Just go the error for the logs:

> RuntimeError (A template needs to have a virtual path in order to be refreshed):
> app/controllers/emails_controller.rb:18:in `block (2 levels) in show'
> app/controllers/emails_controller.rb:17:in `show'

I will work on that.

**Comment by phstc** [comment]
@Chiragverma I did a change, but it seems your email got expired. :/

Could you send that same email again and send the link to me again?

**Comment by chiragverma** [comment]
@phstc , it is blank now - http://preview.putsbox.com/p/lucas/58c6dbc971a82e000c000003.html

Thanks for looking into this

**Comment by phstc** [comment]
@Chiragverma thank you for helping with troubleshooting this!

So basically, what I've found out so far, is that your email does not have the HTML version, only the text. Is there any chance you are sending only the text version?

Check this: http://preview.putsbox.com/p/lucas/58c6dbc971a82e000c000003.text

**Comment by chiragverma** [comment]
Gotcha!! Thanks a lot. I was able to figure this out.. seems like HTML was not turned in my system settings. so it was only sending emails in text format. 

We can close this ticket. Everything seems to work now

**Comment by phstc** [comment]
Nice!

@Chiragverma hm, maybe PutsBox, could show a more specific error message "No HTML version supplied", WDYT? Would that help?

**Comment by chiragverma** [comment]
nice I think that would be awesome.

**Comment by phstc** [comment]
@Chiragverma done 🍻 

Now it returns 404, but shows a more meaningful message "This email does not have a html version".

**Comment by chiragverma** [comment]
@phstc , awesome thank you so much :)
Great tool
