### ISSUE TITLE
How to set up Putsbox locally on my server?

### ISSUE THREAD

**Issue by Pavan-avalara** [phstc/putsbox#7]
hi Pablo, 

Could you point me to instructions\info on how to set up locally?

Thanks!

**Comment by phstc** [comment]
Hi @Pavan-avalara 

You can try to use the same steps from PutsReq: https://github.com/phstc/putsreq#getting-started

**Comment by akash1233** [comment]
hi @phstc i tried following the instructions  https://github.com/phstc/putsreq#getting-started to get putsbox setup locally but getting the following error :
config.secret_key = 'fd57b13120fca3e240951767e00508613bbb0b13f40e862b903250e6a1ff99c8cff9c9130238616ff6baf214024605f8cfd9585ec83ccfeb9e0a5ec276de6a2f'

Please ensure you restarted your application after installing Devise or setting the key.

**Comment by phstc** [comment]
Hi @akash1233 

It's because [`secret_key_base` is set via an ENV variable `ENV['SECRET_TOKEN']`](https://github.com/phstc/putsbox/blob/master/config/initializers/secret_token.rb#L12) , if you replace that with a token for testing purposes, it should work.

**Comment by phstc** [comment]
Hi @akash1233 and @Pavan-avalara 

[I updated the README with instructions to run PutsBox locally](https://github.com/phstc/putsbox#steps-to-run-putsbox-in-development).
