### ISSUE TITLE
"Catch-All" Mailboxes

### ISSUE THREAD

**Issue by sadortun** [phstc/putsbox#8]
Hi Pablo,

It would be a nice feature to be able to generate some sort of catch-all mailboxes.

For example, the bucket is `eleazar_dadel@putsbox.com`, it would be nice to be able to send to  the following addresses : 
- eleazar_dadel+abc@putsbox.com
- eleazar_dadel+def@putsbox.com

Thanks,
Samuel

**Comment by phstc** [comment]
@sadortun interesting idea. I will think on that!

**Comment by phstc** [comment]
@sadortun could you give more details on your use case? How would you use that?

**Comment by sadortun** [comment]
We need to do integration tests and generate 10 000 emails for a list of contact and test if they receive the email within a certain time.  Users needs to have different emails, and creating a bucket for each of them is not needed

**Comment by phstc** [comment]
@sadortun you don't necessarily need to create a bucket through the UI, you can send an email to `whatever-you-want-to@putsbox.com` and it will automatically create a bucket. Does that work for you?

How do you check this:

> they receive the email within a certain time

?

I'm just curious to see how other people are using it 😄

**Comment by sadortun** [comment]
Oh, great,  I did not know that we could create the directly !
