### ISSUE TITLE
Heroku app down

### ISSUE THREAD

**Issue by christrotter** [phstc/putsbox#9]
Just thought I'd mention that your putsbox.com heroku app has been down since at least yesterday afternoon (we tested ~5PM EST, just tried again now, still down).

Good luck!

**Comment by phstc** [comment]
Hey @christrotter 

Thanks for reaching out! 

> code=H82 desc="Free app running time quota exhausted

I guess I can no longer use the Heroku Free Dyno for the whole month 😢 

I've temporally enabled Hobby Dyno (paid one). Could you try it again?

_![](https://avatars2.githubusercontent.com/u/105652?v=3&s=22) needs to enable some "ping" checker for monitoring site down_

**Comment by christrotter** [comment]
Page is loading now, nice!  (I work with David Cohan, by the way.  :) )

We are going to investigate running this on our own infra - currently using it as a part of some legacy system critical path monitoring, having your app goes down makes things angry!  :D

I know folk use pingdom for basic monitoring like that.

By the way, thanks for helping the community by putting this service up for free.

**Comment by christrotter** [comment]
Yup, we just ran through that test now, email working again.  Thanks!

Saw there's another issue where you recommended the putsReq documentation to set up locally, will start investigating.  Good luck with the monitoring!

**Comment by christrotter** [comment]
So after the AWS chaos yesterday, revisiting this.  We are seeing a timeout when getting an email.  Our helper class code is trying to access this url: 
`http://preview.putsbox.com/p/{0}/last.text`
120s timeout, and where the {0} is our random string used.
Edit:  Uh...if this should be a new issue, I can do that....

**Comment by phstc** [comment]
Hi @christrotter 

hm now it reached the SendGrid free tier limits for the month, in a single day, 12k emails, I guess it's a sort of "DDoS". PutsBox uses SendGrid to process emails.

> We are going to investigate running this on our own infra 

Would you guys consider some sort of donation instead? To help with these services (Heroku/SendGrid) costs?

**Comment by christrotter** [comment]
You have created something very useful, it seems. :)

I'll talk to my coworkers and let you know today.

**Comment by phstc** [comment]
@christrotter 🍻 

Should be back again. Sorry for the trouble.

**Comment by phstc** [comment]
I bumped the SendGrid plan as well.

>  in a single day, 12k emails, I guess it's a sort of "DDoS". PutsBox uses SendGrid to process emails.

I guess it's some sort of issue with SendGrid. There were not 12k emails sent today.

> So after the AWS chaos yesterday

Maybe SendGrid is still catching up with that.

**Comment by christrotter** [comment]
@phstc Yeah we can help out - I'll contact you via...uh...LinkedIn I guess and we can figure it out.

**Comment by christrotter** [comment]
O hay, this can be closed.  Our testing once again working without issue!  Thanks again @phstc !!
